name: Unit Tests
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run unit tests
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '24.1.7'
          elixir-version: '1.12.3'
      - run: mix deps.get
      - run: mix test --trace
